### ISSUE TITLE
Can't log into my homeserver - "Error looking up the .well-known endpoint"

### ISSUE THREAD

**Issue by vivlim** [pkulak/matui#15]
Hi, when I try to log into my homeserver (running synapse) I get the following error:

![Image](https://github.com/user-attachments/assets/70279ab0-0727-43d6-b136-af34aeac07ac)

My homeserver's running on `matrix.my.domain`, my account is `@viv:my.domain`, and `curl my.domain/.well-known/matrix/server` returns `{"m.server": "matrix.my.domain:443"}`.
I *believe* this is all set up correctly. It works with other clients I've tried (primarily element/schildichat, fluffychat, nheko)

Do you have any suggestions for how to investigate this? I can debug into this myself but any tips would be really appreciated.

**Comment by pkulak** [comment]
Maybe try running off master? I just updated the entire Matrix library through about a year of updates. Maybe it's fixed now?

What font is that, btw?

**Comment by vivlim** [comment]
ah, I was running `v0.4.5`. unfortunately I'm still getting this error when I run on main. (via `nix run  github:pkulak/matui/7576cd9c5603b38c74579d31232bb23de2b74ce`)

I could try another client using the sdk and see if that makes a difference? I'm used to explicitly specifying my homeserver when logging in, so I was surprised when matui didn't expose that as an option.

Something could also be misconfigured on my end. I did notice this message in [the federation tester](https://federationtester.matrix.org):

> DNS results
>
> server name/.well-known result contains explicit port number: no SRV lookup done

I don't remember why I configured it that way, it's been a few years.

(The font is [Comic Code](https://tosche.net/fonts/comic-code) :))

**Comment by pkulak** [comment]
> I'm used to explicitly specifying my homeserver when logging in, so I was surprised when matui didn't expose that as an option.

Oh good point. When I built this I assumed that just taking it from the username was enough, but I guess there are situations where you may want to specify it explicitly. Should be pretty easy to add one more field to the login screen though.

Haha, of course that's the font. :D

**Comment by pkulak** [comment]
Just looking into this again, and don’t you need the _client_ file as specified here:

https://matrix-org.github.io/matrix-authentication-service/setup/well-known.html

EDIT: ignore the auth stuff, sorry. I’m on mobile, but wanted to write this out before I forgot about it.

**Comment by vivlim** [comment]
Update on this: my synapse instance *was* misconfigured;
`$ curl (domain)/.well-known/matrix/client`
would return
`{"errcode":"M_NOT_FOUND","error":".well-known not available"}`

rather than investigating fixing it I just had my reverse proxy return this instead:
`{"m.homeserver": { "base_url": "https://(domain)" }}`

and now matui works
